In [3]:
import pandas as pd

dados = pd.read_csv('titanic.csv') #importando o arquivo csv

def mulheres_sobreviventes_primeira_classe(dados): #definindo a função
    filter1 = dados[['Name', 'Age','Sex','Pclass','Survived']] #filtrando as colunas que serão utilizadas
    filter1 = filter1.loc[(filter1['Sex'] == 'female')  & (filter1['Pclass'] == 1) & (filter1['Survived'] == 1)] #filtrando os dados
    filter1 = filter1.sort_values(['Name'], ascending=True) #ordenando os dados por ordem alfabética
    filter1.to_csv('mulheres_sobreviventes_primeira_classe.csv', index=False) #salvando o arquivo csv
    print(filter1) #exibindo o resultado

def criancas_sobreviventes(dados):
    filter_children = dados[(dados['Age'] < 12) & (dados['Survived'] == 1)]  
    filter_children = filter_children[['Name', 'Age', 'Survived']]  # Selecionando as colunas relevantes
    filter_children = filter_children.sort_values(['Age'], ascending=True)  # Ordenando por idade
    filter_children.to_csv('criancas_sobreviventes.csv', index=False) 
    print(filter_children) 

def idosos_a_bordo(dados):
    filter_idosos = dados[dados['Age'] > 60]  
    filter_idosos = filter_idosos[['Name', 'Age', 'Survived']] 
    filter_idosos = filter_idosos.sort_values(['Name'], ascending=True)
    filter_idosos.to_csv('idosos_a_bordo.csv', index=False)
    print(filter_idosos)

# Chamando as funções para exibir os resultados
mulheres_sobreviventes_primeira_classe(dados)
criancas_sobreviventes(dados)
idosos_a_bordo(dados)

                                                  Name   Age     Sex  Pclass  \
730                      Allen, Miss. Elisabeth Walton  29.0  female       1
275                  Andrews, Miss. Kornelia Theodosia  63.0  female       1
571      Appleton, Mrs. Edward Dale (Charlotte Lamson)  53.0  female       1
700  Astor, Mrs. John Jacob (Madeleine Talmadge Force)  18.0  female       1
369                      Aubart, Mme. Leontine Pauline  24.0  female       1
..                                                 ...   ...     ...     ...
258                                   Ward, Miss. Anna  35.0  female       1
366   Warren, Mrs. Frank Manley (Anna Sophia Atkinson)  60.0  female       1
318                           Wick, Miss. Mary Natalie  31.0  female       1
856         Wick, Mrs. George Dennick (Mary Hitchcock)  45.0  female       1
325                           Young, Miss. Marie Grice  36.0  female       1

     Survived
730         1
275         1
571         1
700         1
369         1
..        ...
258         1
366         1
318         1
856         1
325         1

[91 rows x 5 columns]
                                                Name    Age  Survived
803                  Thomas, Master. Assad Alexander   0.42         1
755                        Hamalainen, Master. Viljo   0.67         1
644                           Baclini, Miss. Eugenie   0.75         1
469                    Baclini, Miss. Helene Barbara   0.75         1
831                  Richards, Master. George Sibley   0.83         1
78                     Caldwell, Master. Alden Gates   0.83         1
305                   Allison, Master. Hudson Trevor   0.92         1
381                      Nakid, Miss. Maria ("Mary")   1.00         1
788                       Dean, Master. Bertram Vere   1.00         1
827                            Mallet, Master. Andre   1.00         1
183                        Becker, Master. Richard F   1.00         1
172                     Johnson, Miss. Eleanor Ileen   1.00         1
479                         Hirvonen, Miss. Hildur E   2.00         1
340                   Navratil, Master. Edmond Roger   2.00         1
530                         Quick, Miss. Phyllis May   2.00         1
407                   Richards, Master. William Rowe   3.00         1
261                Asplund, Master. Edvin Rojj Felix   3.00         1
348           Coutts, Master. William Loch "William"   3.00         1
193                       Navratil, Master. Michel M   3.00         1
43          Laroche, Miss. Simonne Marie Anne Andree   3.00         1
750                                Wells, Miss. Joan   4.00         1
618                      Becker, Miss. Marion Louise   4.00         1
445                        Dodge, Master. Washington   4.00         1
691                               Karun, Miss. Manca   4.00         1
184              Kink-Heilmann, Miss. Luise Gretchen   4.00         1
10                   Sandstrom, Miss. Marguerite Rut   4.00         1
869                  Johnson, Master. Harold Theodor   4.00         1
777                    Emanuel, Miss. Virginia Ethel   5.00         1
448                   Baclini, Miss. Marie Catherine   5.00         1
233                   Asplund, Miss. Lillian Gertrud   5.00         1
58                      West, Miss. Constance Mirium   5.00         1
720                Harper, Miss. Annie Jessie "Nina"   6.00         1
751                              Moor, Master. Meier   6.00         1
535                           Hart, Miss. Eva Miriam   7.00         1
237                 Collyer, Miss. Marjorie "Lottie"   8.00         1
549                   Davies, Master. John Morgan Jr   8.00         1
489            Coutts, Master. Eden Leslie "Neville"   9.00         1
165  Goldsmith, Master. Frank John William "Frankie"   9.00         1
802              Carter, Master. William Thornton II  11.00         1
                                          Name   Age  Survived
275          Andrews, Miss. Kornelia Theodosia  63.0         1
493                    Artagaveytia, Mr. Ramon  71.0         0
630       Barkworth, Mr. Algernon Henry Wilson  80.0         1
116                       Connors, Mr. Patrick  70.5         0
745               Crosby, Capt. Edward Gifford  70.0         0
280                           Duane, Mr. Frank  65.0         0
438                          Fortune, Mr. Mark  64.0         0
96                   Goldschmidt, Mr. George B  71.0         0
570                         Harris, Mr. George  62.0         1
456                  Millet, Mr. Francis Davis  65.0         0
672                Mitchell, Mr. Henry Michael  70.0         0
545               Nicholson, Mr. Arthur Ernest  64.0         0
326                  Nysveen, Mr. Johan Hansen  61.0         0
54              Ostby, Mr. Engelhart Cornelius  65.0         0
252                  Stead, Mr. William Thomas  62.0         0
829  Stone, Mrs. George Nelson (Martha Evelyn)  62.0         1
625                      Sutton, Mr. Frederick  61.0         0
851                        Svensson, Mr. Johan  74.0         0
483                     Turkula, Mrs. (Hedwig)  63.0         1
170                  Van der hoef, Mr. Wyckoff  61.0         0
33                       Wheadon, Mr. Edward H  66.0         0
555                         Wright, Mr. George  62.0         0